### ISSUE TITLE
A6: Short summary in an article about updates in July and publication from social networks(ENG)

### ISSUE THREAD

**Issue by Rodzher** [bit-country/ambassador#1841]
https://kudratillaev-korol.medium.com/update-of-the-development-of-the-middle-metabus-in-july-2021-c45b5eae0c4?source=social.tw
https://twitter.com/K_C_A_N2001/status/1422768277961445378
https://l.facebook.com/l.php?u=https%3A%2F%2Flink.medium.com%2FRkgcwA9brib&h=AT3yyNgKE-_YhFdfPmeJgCpLLUfEqOzOqd5Iqwvq6eyeUF-r6Qyf5leweqip9NTaMuE4ddXDQpMrqNfT-rW7QZLfPes0pK3_he1WnJHRJKTlNgoRG9uwVdirphA

**Comment by MiaLuAKL** [comment]
Please note this issue didn't get approved by the B.C content team.  Again thanks for your effort.
